// <auto-generated />
using System;
using FleetOps.Stock.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FleetOps.Stock.Persistence.Migrations
{
    [DbContext(typeof(StockDbContext))]
    [Migration("20260903113133_IlkSurum")]
    partial class IlkSurum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("stock")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FleetOps.Stock.Domain.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("zone");

                    b.HasKey("Id")
                        .HasName("pk_location");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_location_code");

                    b.ToTable("location", "stock");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000001"),
                            Code = "KABUL-01",
                            Zone = "Kabul"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000002"),
                            Code = "RAF-A1",
                            Zone = "Depo"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000003"),
                            Code = "RAF-B2",
                            Zone = "Depo"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000004"),
                            Code = "SEVK-01",
                            Zone = "Sevkiyat"
                        });
                });

            modelBuilder.Entity("FleetOps.Stock.Domain.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FromLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_location_id");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("material_code");

                    b.Property<DateTime>("MovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("moved_at_utc");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SourceTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_task_id");

                    b.Property<Guid>("ToLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_location_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_movement");

                    b.HasIndex("FromLocationId")
                        .HasDatabaseName("ix_stock_movement_from_location_id");

                    b.HasIndex("MovedAtUtc")
                        .HasDatabaseName("ix_stock_movement_moved_at_utc");

                    b.HasIndex("ToLocationId")
                        .HasDatabaseName("ix_stock_movement_to_location_id");

                    b.ToTable("stock_movement", "stock");
                });

            modelBuilder.Entity("FleetOps.Stock.Infrastructure.ProcessedIntegrationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_processed_integration_event");

                    b.ToTable("processed_integration_event", "stock");
                });

            modelBuilder.Entity("FleetOps.Stock.Domain.StockMovement", b =>
                {
                    b.HasOne("FleetOps.Stock.Domain.Location", null)
                        .WithMany()
                        .HasForeignKey("FromLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movement_location_from_location_id");

                    b.HasOne("FleetOps.Stock.Domain.Location", null)
                        .WithMany()
                        .HasForeignKey("ToLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movement_location_to_location_id");
                });
#pragma warning restore 612, 618
        }
    }
}
