// <auto-generated />
using System;
using FleetOps.Api.Auth;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FleetOps.Api.Auth.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    partial class AuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("auth")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FleetOps.Api.Auth.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_app_user");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ix_app_user_user_name");

                    b.ToTable("app_user", "auth");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-0000-0000-0000-000000000001"),
                            PasswordHash = "100000.u1dXkDE+WT5SEH2bOdEpZg==.fLwykOL+TgFQ7akkw/MlEPmcBiWkUBi/kxrCkh2WUg8=",
                            Role = "Operator",
                            UserName = "operator"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-0000-0000-0000-000000000002"),
                            PasswordHash = "100000.M5ugf+wFXLnNWojnB4Ok/Q==.dqXIJoJIK5JlCvxEKScj6oTIEkDUkArvkzqkICwGZAQ=",
                            Role = "Supervisor",
                            UserName = "supervisor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
